# Generated by Django 5.0.6 on 2024-05-26 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="cars/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HB", "HATCHBACK"),
                            ("SE", "SEDAN"),
                            ("X", "XUV"),
                            ("S", "SUV"),
                            ("PER", "PERFORMANCE"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
