# Generated by Django 5.0.6 on 2024-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carvariety",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
